helm:
  parameters:
  - name: image.name
    value: harbor-dev-repo.ops.io/podinfo-sample-app
    forcestring: true
  - name: image.tag
    value: develop@sha256:c5000b2801a2e7eef05f2426dadf26f3a7120139030286e693d3f4af07975788
    forcestring: true
