helm:
  parameters:
  - name: image.name
    value: harbor-dev-repo.ops.io/podinfo-sample-app
    forcestring: true
  - name: image.tag
    value: develop@sha256:6fa3f99099ed458fd7c58aa039fd4f53620024031430e913e21790b6cadc526d
    forcestring: true
